# Docker Compose pour Vitest UI uniquement
version: '3.8'

services:
  # Container pour Vitest UI
  test-ui:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: convention-test-ui
    environment:
      NODE_ENV: "test"
      CI: "false"
      JWT_SECRET: "test_jwt_secret"
    volumes:
      - ./app:/app/app:cached
      - ./server:/app/server:cached
      - ./tests:/app/tests:cached
      - ./scripts:/app/scripts:cached
      - ./prisma:/app/prisma:cached
      - ./public:/app/public:cached
      - ./nuxt.config.ts:/app/nuxt.config.ts:cached
      - ./vitest.config.ts:/app/vitest.config.ts:cached
      - ./vitest.config.simple.ts:/app/vitest.config.simple.ts:cached
      - ./vitest.config.ui.ts:/app/vitest.config.ui.ts:cached
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command:
      - sh
      - -c
      - |
        mkdir -p /app/public/uploads
        npx vitest --ui --config vitest.config.ui.ts

volumes:
  node_modules:
    driver: local