# Docker Compose pour Vitest UI uniquement
version: '3.8'

services:
  # Container pour Vitest UI
  test-ui:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: convention-test-ui
    environment:
      NODE_ENV: 'test'
      CI: 'false'
    volumes:
      - ./app:/app/app:cached
      - ./server:/app/server:cached
      - ./test:/app/test:cached
      - ./scripts:/app/scripts:cached
      - ./prisma:/app/prisma:cached
      - ./public:/app/public:cached
      - ./nuxt.config.ts:/app/nuxt.config.ts:cached
      - ./vitest.config.unit.ts:/app/vitest.config.unit.ts:cached
      - node_modules:/app/node_modules
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    command:
      - sh
      - -c
      - |
        mkdir -p /app/public/uploads
        if [ ! -x node_modules/.bin/vitest ]; then
          echo "node_modules absent: installation des dépendances..."
          npm ci
        fi
        npx vitest --ui --config vitest.config.unit.ts

volumes:
  node_modules:
    driver: local
