version: '3.8'

services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: convention-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: convention_db
      MYSQL_USER: convention_user
      MYSQL_PASSWORD: convention_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - convention-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Application Nuxt.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: convention-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Base de données
      DATABASE_URL: "mysql://convention_user:convention_password@database:3306/convention_db"
      
      # JWT Secret
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      
      # Nuxt
      NUXT_HOST: "0.0.0.0"
      NUXT_PORT: "3000"
      NODE_ENV: "production"
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - convention-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Adminer pour gérer la base de données (optionnel)
  adminer:
    image: adminer:latest
    container_name: convention-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - convention-network
    depends_on:
      - database

volumes:
  mysql_data:
    driver: local

networks:
  convention-network:
    driver: bridge