# Docker Compose pour Convention de Jonglerie
services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: convention-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: convention_db
      MYSQL_USER: convention_user
      MYSQL_PASSWORD: convention_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Application Nuxt.js
  app:
    build: .
    container_name: convention-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://convention_user:convention_password@database:3306/convention_db"
      JWT_SECRET: "mon_secret_jwt_de_convention_de_jonglerie_super_long"
      NUXT_HOST: "0.0.0.0"
      NUXT_PORT: "3000"
      NODE_ENV: "production"
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      database:
        condition: service_healthy

  # Interface d'administration base de données
  adminer:
    image: adminer:latest
    container_name: convention-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  mysql_data:
    driver: local