version: '3.8'

# Stack Convention de Jonglerie pour Portainer
# À utiliser dans Portainer Stacks

services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeme123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-convention_db}
      MYSQL_USER: ${MYSQL_USER:-convention_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme456}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - convention-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Application Nuxt.js
  app:
    image: powange/convention-de-jonglerie:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER:-convention_user}:${MYSQL_PASSWORD:-changeme456}@database:3306/${MYSQL_DATABASE:-convention_db}"
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-32-chars-min}
      NODE_ENV: production
      APP_URL: ${APP_URL:-http://localhost:3000}
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - convention-network
    depends_on:
      database:
        condition: service_healthy

  # Interface d'administration base de données
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - convention-network
    depends_on:
      - database

volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local

networks:
  convention-network:
    driver: bridge