version: '3.8'

# Stack simplifiée pour Portainer - sans build
# L'image de l'application doit être construite séparément

services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeme123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-convention_db}
      MYSQL_USER: ${MYSQL_USER:-convention_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme456}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Retirer cette ligne si vous n'avez pas le script d'init
      # - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - convention-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Interface d'administration base de données
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - convention-network
    depends_on:
      - database

volumes:
  mysql_data:
    driver: local

networks:
  convention-network:
    driver: bridge