version: '3'

services:
  # Test simple avec MySQL uniquement
  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpass123
      MYSQL_DATABASE: testdb
    ports:
      - "3399:3306"