-- AlterTable
ALTER TABLE `EditionMarker` MODIFY `markerType` ENUM('CAMPING', 'PARKING', 'SHOWS', 'WORKSHOPS', 'FOOD', 'MARKET', 'ENTRANCE', 'TOILETS', 'INFO', 'GYM', 'OTHER') NOT NULL DEFAULT 'OTHER';

-- AlterTable
ALTER TABLE `EditionZone` MODIFY `zoneType` ENUM('CAMPING', 'PARKING', 'SHOWS', 'WORKSHOPS', 'FOOD', 'MARKET', 'ENTRANCE', 'TOILETS', 'INFO', 'GYM', 'OTHER') NOT NULL DEFAULT 'OTHER';
