-- AlterTable
ALTER TABLE `Conversation` MODIFY `editionId` INTEGER NULL,
    MODIFY `type` ENUM('TEAM_GROUP', 'TEAM_LEADER_PRIVATE', 'VOLUNTEER_TO_ORGANIZERS', 'ORGANIZERS_GROUP', 'PRIVATE') NOT NULL;
