name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  DATABASE_URL: mysql://root:rootpassword@localhost:3306/convention_db_test
  NUXT_SESSION_PASSWORD: test_session_password_32_chars_min
  # Désactiver les emails en test
  SEND_EMAILS: false
  # Bypass reCAPTCHA en test
  NUXT_RECAPTCHA_DEV_BYPASS: true

jobs:
  # Job pour installer les dépendances une seule fois
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      deps-cache-key: ${{ steps.cache-keys.outputs.deps }}
      prisma-cache-key: ${{ steps.cache-keys.outputs.prisma }}
      nuxt-cache-key: ${{ steps.cache-keys.outputs.nuxt }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Generate cache keys
        id: cache-keys
        run: |
          echo "deps=${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT
          echo "prisma=${{ runner.os }}-prisma-${{ hashFiles('prisma/schema.prisma') }}-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT
          echo "nuxt=${{ runner.os }}-nuxt-${{ hashFiles('nuxt.config.ts', 'tsconfig.json', 'app.config.ts') }}" >> $GITHUB_OUTPUT

      - name: Cache Node dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ steps.cache-keys.outputs.deps }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Cache Prisma client
        id: cache-prisma
        uses: actions/cache@v4
        with:
          path: node_modules/.prisma
          key: ${{ steps.cache-keys.outputs.prisma }}
          restore-keys: |
            ${{ runner.os }}-prisma-

      - name: Cache Nuxt build
        id: cache-nuxt
        uses: actions/cache@v4
        with:
          path: .nuxt
          key: ${{ steps.cache-keys.outputs.nuxt }}
          restore-keys: |
            ${{ runner.os }}-nuxt-

      - name: Install dependencies (if not cached)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      - name: Generate Prisma client
        if: steps.cache-prisma.outputs.cache-hit != 'true'
        run: npx prisma generate

      # Générer les fichiers Nuxt nécessaires pour les tests (si pas en cache)
      - name: Prepare Nuxt
        if: steps.cache-nuxt.outputs.cache-hit != 'true'
        run: npx nuxi prepare

      # Sauvegarder les dépendances comme artifact pour les autres jobs
      - name: Upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: deps-${{ github.run_id }}
          path: |
            node_modules
            .nuxt
            package.json
            package-lock.json
          retention-days: 1

  # Job pour le linting (rapide, pas besoin de DB)
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Restore Node dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ needs.setup.outputs.deps-cache-key }}
          fail-on-cache-miss: true

      - name: Restore Prisma client
        uses: actions/cache@v4
        with:
          path: node_modules/.prisma
          key: ${{ needs.setup.outputs.prisma-cache-key }}
          fail-on-cache-miss: true

      - name: Restore Nuxt build
        uses: actions/cache@v4
        with:
          path: .nuxt
          key: ${{ needs.setup.outputs.nuxt-cache-key }}
          fail-on-cache-miss: true

      - name: Run linting
        run: npm run lint

  # Job pour valider que le build fonctionne
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Restore Node dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ needs.setup.outputs.deps-cache-key }}
          fail-on-cache-miss: true

      - name: Restore Prisma client
        uses: actions/cache@v4
        with:
          path: node_modules/.prisma
          key: ${{ needs.setup.outputs.prisma-cache-key }}
          fail-on-cache-miss: true

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            .nuxt/
            .output/
          retention-days: 7

  # Tests en parallèle avec matrice
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [setup, lint, build] # Attendre setup, lint et build avant de lancer les tests

    strategy:
      fail-fast: false # Continue même si un test échoue
      matrix:
        test-group:
          - { name: 'unit', cmd: 'npm run test:unit:run', db: false }
          - { name: 'nuxt', cmd: 'npm run test:nuxt:run', db: false }
          - { name: 'e2e', cmd: 'npm run test:e2e:run', db: false }
          - { name: 'database', cmd: 'npm run test:db:run', db: true }

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: convention_db_test
          MYSQL_USER: convention_user
          MYSQL_PASSWORD: convention_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Restore Node dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ needs.setup.outputs.deps-cache-key }}
          fail-on-cache-miss: true

      - name: Restore Prisma client
        uses: actions/cache@v4
        with:
          path: node_modules/.prisma
          key: ${{ needs.setup.outputs.prisma-cache-key }}
          fail-on-cache-miss: true

      - name: Restore Nuxt build
        uses: actions/cache@v4
        with:
          path: .nuxt
          key: ${{ needs.setup.outputs.nuxt-cache-key }}
          fail-on-cache-miss: true

      - name: Setup database schema (DB tests only)
        if: matrix.test-group.db
        run: |
          # Reset la base complètement pour éviter les conflits de migration
          npx prisma migrate reset --force --skip-seed

      - name: Run tests - ${{ matrix.test-group.name }}
        run: ${{ matrix.test-group.cmd }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-group.name }}-${{ github.run_id }}
          path: |
            test-results/
            coverage/
            .nuxt/
          retention-days: 7

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ matrix.test-group.name }}-${{ github.run_id }}
          path: coverage/
          retention-days: 30
