name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit + nuxt + e2e
        run: npm run test:all

      - name: Start test database
        run: npm run test:setup

      - name: Run DB integration tests
        run: npm run test:db:run

      - name: Stop test database
        if: always()
        run: npm run test:teardown
