name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  DATABASE_URL: mysql://root:rootpassword@localhost:3306/convention_db_test
  NUXT_SESSION_PASSWORD: test_session_password_32_chars_min
  # Désactiver les emails en test
  SEND_EMAILS: false
  # Bypass reCAPTCHA en test
  NUXT_RECAPTCHA_DEV_BYPASS: true

jobs:
  # Job pour installer les dépendances une seule fois
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Generate cache key
        id: cache-key
        run: echo "key=${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ hashFiles('prisma/schema.prisma') }}" >> $GITHUB_OUTPUT

      - name: Cache dependencies and Prisma
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
            node_modules/.prisma
            .nuxt
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-
            ${{ runner.os }}-node-

      - name: Install dependencies (if not cached)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      - name: Generate Prisma client
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npx prisma generate

      # Générer les fichiers Nuxt nécessaires pour les tests
      - name: Prepare Nuxt
        run: npx nuxi prepare

      # Sauvegarder les dépendances comme artifact pour les autres jobs
      - name: Upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: deps-${{ github.run_id }}
          path: |
            node_modules
            .nuxt
            package.json
            package-lock.json
          retention-days: 1

  # Job pour le linting (rapide, pas besoin de DB)
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
            node_modules/.prisma
            .nuxt
          key: ${{ needs.setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Run linting
        run: npm run lint

  # Tests en parallèle avec matrice
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [setup, lint] # Attendre setup et lint avant de lancer les tests

    strategy:
      fail-fast: false # Continue même si un test échoue
      matrix:
        test-group:
          - { name: 'unit', cmd: 'npm run test:unit:run', db: false }
          - { name: 'nuxt', cmd: 'npm run test:nuxt:run', db: false }
          - { name: 'e2e', cmd: 'npm run test:e2e:run', db: false }
          - { name: 'database', cmd: 'npm run test:db:run', db: true }

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: convention_db_test
          MYSQL_USER: convention_user
          MYSQL_PASSWORD: convention_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
            node_modules/.prisma
            .nuxt
          key: ${{ needs.setup.outputs.cache-key }}
          fail-on-cache-miss: true

      - name: Setup database schema (DB tests only)
        if: matrix.test-group.db
        run: |
          # Reset la base complètement pour éviter les conflits de migration
          npx prisma migrate reset --force --skip-seed

      - name: Run tests - ${{ matrix.test-group.name }}
        run: ${{ matrix.test-group.cmd }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-group.name }}-${{ github.run_id }}
          path: |
            test-results/
            coverage/
            .nuxt/
          retention-days: 7

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ matrix.test-group.name }}-${{ github.run_id }}
          path: coverage/
          retention-days: 30
